### ISSUE TITLE
DllNotFoundException: gdiplus.dll

### ISSUE THREAD

**Issue by ghost** [GlitchEnzo/UnityPSDLayoutTool#1]
Hi,when i use the tool, i get a error : DllNotFoundException: gdiplus.dll. how to fix it!
OS is Mac OS X.
![23dc3834-c30e-4061-9a1b-cb10c2dd35ec](https://cloud.githubusercontent.com/assets/10728242/6429810/fd254130-c024-11e4-8abb-bf80bd8a2e2a.png)

**Comment by GlitchEnzo** [comment]
First, I'm sorry you encountered this issue.  I'm a Windows developer, so it's hard to properly test on a Mac.

It appears that the Mono System.Drawing.dll that I'm using has an internal dependency on gdiplus.dll, which is Windows only.  That is very odd to me and I see that other Unity users have run into the same problem on other projects, but there doesn't seem to be a good solution.

I can attempt to rewrite my code to not have the System.Drawing depencency anymore, but that might take some time.

**Comment by GlitchEnzo** [comment]
This turned out not to be that difficult or time-consuming.  The PSD Layout Tool is no longer dependent on System.Drawing so it should work on a Mac!

**Comment by ghost** [comment]
Thanks! it's works well!
